site_name: Gráficos interativos com Python Plotly e Dash - Infinity School
use_directory_urls: false

copyright: Copyright &copy; 2022 Fernando Ferraz Ribeiro

theme:
  features:
    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs/overrides
  favicon: figs/favicon2.png
  logo: figs/favicon2.png


  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_url: "https://255ribeiro.github.io/infinity_ws_plotly_dash/"
repo_url: "https://github.com/255ribeiro/infinity_ws_plotly_dash"
repo_name: "255ribeiro/infinity_ws_plotly_dash" 

nav:
  - Home: index.md
  - Virtual environment: ./venv_basic/venv.md


  - Estruturas de dados: ./data_structures/datastructures.ipynb
  - Numpy básico: ./cientif_py/numpy_intro.ipynb
  - Jupyter básico: ./cientif_py/jupyter_intro.ipynb
  - Pandas:
    - Introdução pt1: ./pandas_intro/pandas_intro_01.ipynb
    - Introdução pt2: ./pandas_intro/pandas_intro_02.ipynb
    - Introdução pt3: ./pandas_intro/pandas_intro_03.ipynb
    - Introdução pt4: ./pandas_intro/pandas_intro_04.ipynb
  - Flask conceito: ./flask_dash/flask/hello_flask.ipynb
  - Plotly:
    - Quick Start: ./plotly_basics/plotly_basics.ipynb
    - Data e Layout: ./plotly_basics/data_e_layout.ipynb
    - Bar Chart: ./plotly/bar_chart.ipynb
    - Box Plot: ./plotly/box_plot.ipynb
    - Bubble Chart: plotly/bubble_chart.ipynb
    - Histograma: ./plotly/histogram.ipynb
  
  
 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter:
      kernel_name:
      include: [] #["*.py", "*.ipynb"]
      #ignore: ["./flask/hello_flask.ipynb"]
      execute: False
      execute_ignore: "./flask_dash/*/*"
      include_source: True
      


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope
        link: mailto:ffribeiro@gmail.com
