site_name: Gráficos interativos com Python Plotly e Dash - Infinity School
use_directory_urls: false

copyright: Copyright &copy; 2022 Fernando Ferraz Ribeiro

theme:
  features:
    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs/overrides
  favicon: figs/favicon.jpg
  logo: figs/favicon.jpg


  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_url: "https://255ribeiro.github.io/infinity_ws_plotly_dash/"
repo_url: "https://github.com/255ribeiro/infinity_ws_plotly_dash"
repo_name: "255ribeiro/infinity_ws_plotly_dash" 

nav:
  - Home: index.md
  - Virtual environment: ./venv_basic/venv.md


  - Estruturas de dados: ./data_structures/datastructures.ipynb
  - Listas:
    - Examplo 01: ./python_example/list_examples.py
    - Examplo 02: ./python_example/list_example_02.py
    - Examplo 03: ./python_example/list_example_03.py
  - Numpy básico: ./cientif_py/numpy_intro.ipynb
  - Jupyter básico: ./cientif_py/jupyter_intro.ipynb
  - Pandas:

    - Introdução pt1: ./pandas_intro/pandas_intro.ipynb
    - Introdução pt2: ./pandas_intro/pandas_intro_02.ipynb
    - Introdução pt3: ./pandas_intro/pandas_intro_03.ipynb
    - Introdução pt4: ./pandas_intro/pandas_intro_04.ipynb
  - Flask conceito: ./flask/hello_flask.ipynb
  
 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter:
      kernel_name:
      execute: True
      include_source: True
      


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope
        link: mailto:ffribeiro@gmail.com
